//SPDX-License-Identifier: Unlicense
pragma solidity >=0.8.4 <0.9.0;

/// @notice Errors and events that can be used during the revelation stage.
interface ITheLodgeRevelationHandler {
  /// @notice Thrown when configuring the VRF Coordinator using the zero address.
  error ZeroAddress();

  /// @notice Thrown when there's a call to fulfill the randomness, but a previous
  /// call was already made.
  error AlreadyRevealed();

  /// @notice Emitted when the randomness is fulfilled.
  /// @param number The random number generated by the VRF Coordinator.
  event Revealed(uint256 number);
}
